title: CS10 Fall 2023
tagline: The Beauty and Joy of Computing
description: A gentle, but thorough introduction to computer science.
author: Imen Guechtouli
baseurl: /sp23 # the subpath of your site, e.g. /blog
url: https://cs10.org
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

logo: "./assets/images/bjc.png"

# Theme settings
remote_theme: pmarsceill/just-the-docs@v0.3.3
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links_new_tab: true
ga_tracking: UA-47210910-1
external_navigation:
  - title: Snap!
    url: https://snap.berkeley.edu/
  - title: Ed Discussion
    url: 
  - title: Gradescope
    url: 
  - title: Ohyay
    url: https://ohyay.co/s/cs10/
footer_content:

################################################
# Custom Data
bCourses: 
labsCourse: cs10_fa21.html
ed_id: 
labsurl: https://cs10.org/

###### TODO: UPDATE THESE, CURRENTLY UNUSED
# This section controlls the interactive google calendar.
# Should be in MomentJS format
startDate: 2023-01-15 # First Sunday
endDate:   2023-05-20 # Last Saturday

# Change the calendar to show Sun-Sat instead of M-F when an exam is near
questDate: 
midtermDate: 
finalDate: 
# from console.developers.google.com
# This key can be public and is tied to a users calendar accesses
# whoever this key belongs to should have access to the CS10 galendars.
gcalAPIKey: 

###############################################
# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag

just_the_docs:
  collections:
